Feature/projects dynamic
KhaledHN/portfolio-nextjs pull request #4
Opened 2023-07-18 16:59 UTC by KhaledHN

What change:

1. Create a dummy projects API
2. Dynamic route for projects detail page
3. Get projects dynamicly from the API
4. UI enhancements
5. Dynamic navbar and drawer navbar

2023-07-22 13:42 UTC, HazemKhaled requested changes

2023-07-22 13:42 UTC, HazemKhaled commented on pages/projects/[slug].tsx
> +import projectsData from "../api/Projects.json";
Get data from the API

2023-07-23 10:50 UTC, closed without merging

2023-07-26 18:30 UTC, ismail9k commented on components/NavBar/DrawerNav.tsx
> +                <li onClick={handleNav} className="py-4 text-sm">
Navigation should always be on <a /> tags

2023-07-26 18:30 UTC, ismail9k commented on components/NavBar/DrawerNav.tsx
> +              <Link href="">
Don't use empty href, it will not support open in new tab

2023-07-26 18:31 UTC, ismail9k commented on components/NavBar/DrawerNav.tsx
> +                <div className="rounded-full shadow-lg shadow-gray-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300">
Instead of duplicate classes `rounded-full shadow-lg shadow-gray-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300` use tailwind apply

https://tailwindcss.com/docs/reusing-styles

2023-07-26 18:32 UTC, ismail9k commented on components/NavBar/DrawerNav.tsx
> +                  <Link href="https://mail.google.com/mail/u/0/#sent?compose=CllgCJqXxhFbpRhxNlVPhLsSwWrlkqhLtXRKFkCtRfxVBnfFHZrnmZNmzdTStkWKskMNjXHPRhg">
Check mailto: https://www.w3docs.com/snippets/html/how-to-create-mailto-links.html

2023-07-26 18:35 UTC, ismail9k commented on components/NavBar/Navbar.tsx
> +  const checkScrollTop = () => {
You might want to wrap your checkScrollTop function with useCallback hook to memoize the function and avoid unnecessary re-renders. It's also important to add checkScrollTop to the dependency array of your useEffect to ensure that the event listener always has the most recent version of the function

```
  const checkScrollTop = useCallback(() => {
    setShadow(window.scrollY >= 90);
  }, []);
  ````

2023-07-26 18:38 UTC, ismail9k commented on components/Projects/Projects.tsx
> +  }, []);
```const fetchProjects = async () => {
  try {
    const res = await fetch("/api/projects");
    if (!res.ok) {
      throw new Error("Failed to fetch project data");
    }
    const data = await res.json();
    setProjectsData(data.projects);
  } catch (error) {
    setError(error.message);
  } finally {
    setLoading(false);
  }
};

// You would call this in a useEffect like so:
useEffect(() => {
  fetchProjects();
}, []);```