Dynamic Projects
KhaledHN/portfolio-nextjs pull request #6
Opened 2023-07-23 07:11 UTC by KhaledHN

2023-07-23 10:34 UTC, HazemKhaled requested changes

2023-07-23 10:34 UTC, HazemKhaled commented on pages/projects/[slug].jsx
> +import { useEffect, useState } from "react";
combine this with the first line

2023-07-26 07:00 UTC, HazemKhaled commented on pages/projects/[slug].jsx
> +import { useEffect, useState } from "react";
Any update @KhaledHN ?

2023-07-26 13:04 UTC, KhaledHN commented on pages/projects/[slug].jsx
> +import { useEffect, useState } from "react";
Done

2023-07-26 13:39 UTC, HazemKhaled approved these changes

2023-07-26 16:06 UTC, merged